[package]
name = "envlang"
version = "0.5.7"
edition = "2021"

[lib]
name = "envlang"
path = "src/lib.rs"

[[bin]]
name = "envlang"
path = "src/main.rs"

[dependencies]
unicode-segmentation = "1.12.0"
